name: testng-runner

on:
  schedule:
    - cron: '30 11 * * *'
  push:
    branches-ignore:
      - develop
    branches:
      - main
      - 'realeses/**'

  pull_request:
    types:
      - labeled
      - opened
      - synchronize

  issues:
    types:
      - opened
      - labeled
