name: Provide inputs to workflow

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'maven profile - select your browser'
        options:
          - 'chrome'
          - 'firefox'

        required: true
        default: 'chrome'
        type: choice
      remoteURL:
        description: 'selenoid url if hosted outside'
        required: true
        default: 'http://localhost:4444/wd/hub'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run the tests
        run:
          mvn clean test -DBrowser=${{ github.event.inputs.browser }}
