name: Provide inputs to workflow

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'maven profile - select your browser'
        options:
          - 'chrome'
          - 'firefox'

        required: true
        default: 'chrome'
        type: choice
      remoteURL:
        description: 'selenoid url if hosted outside'
        required: true
        default: 'http://localhost:4444/wd/hub'

      executionType:
        description: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Run the maven tests
        run:
          mvn clean test -DBrowser=${{ github.event.inputs.browser }}
